### ISSUE TITLE
Enforce username to be unique

### ISSUE THREAD

**Issue by eugenesmkn** [eugenesimakin/link-sharing-app#12]
The username as a part of public user url should be unique when provided on registration.

**Comment by eugenesmkn** [comment]
Note: 
The unique property is already enforced. Need to create good UX.

```java
@Column(name = "username", nullable = false, unique = true)
```

**Comment by Washubrnfg85** [comment]
I noticed that. But I did it the same way as email validation - with conditional check in Controller. 
If you assume something else here, please tell me. Maybe I'll learn some new stuff.
