### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by eugenesmkn** [eugenesimakin/link-sharing-app#22]
Make application available as docker image. This will make deployment an easy task.

Example of a guide: https://spring.io/guides/topicals/spring-boot-docker

Acceptance criteria:
- Dockerfile
- Docker image of the app should be publicly available at https://hub.docker.com/

**Comment by Washubrnfg85** [comment]
Dockerfile pushed to main.
Link to image: https://hub.docker.com/r/archpj/link-sharing-app
