### ISSUE TITLE
Load testing of public pages functionality

### ISSUE THREAD

**Issue by eugenesmkn** [eugenesimakin/link-sharing-app#24]
Scenario:
- Retrieve usernames from some storage.
- Choose username.
- Generate load.

**Comment by Washubrnfg85** [comment]
First of all 1000 users and their details were uploaded into psql DB.
Than test was activated: 1000 requests to all public pages. Worked very fast:
![image](https://github.com/eugenesimakin/link-sharing-app/assets/32965556/524be621-8b88-4c58-9525-5a0463d82660)
