### ISSUE TITLE
Implement validation rules for Login and Registration pages

### ISSUE THREAD

**Issue by eugenesmkn** [eugenesimakin/link-sharing-app#3]
Login page:

- [x] Empty email and password are not allowed.
- [x] The email should be validated. We need to verify that it consists of these parts: the username (not necessary the same as `User.username`), the separator `@` and the domain. 

Registration page:

- [x] Empty username, email and password are not allowed.

**Comment by Washubrnfg85** [comment]
I think email validation should be provided during registration. So as Username and Password.
In this case there is no need to validate data from login page.
Consider it while reviewing my code.

**Comment by eugenesimakin** [comment]
Validation rules should be implemented both on the frontend and the backend sides.
You could refer to this article for frontend validation - https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
