### ISSUE TITLE
Save (update) user profile details

### ISSUE THREAD

**Issue by eugenesmkn** [eugenesimakin/link-sharing-app#4]
- [x] Users should be able to save or update their first name, last name and email. This email could differ from the email which is used for authentication.

**Comment by Washubrnfg85** [comment]
**Off topic**
Basic thoughts:
1. There should be two tables: Users and Links.
2. Relationships between them should be like one-to-many. One user can own many links. Link shouldn't have any limitations or additional fields to store data about owners.

**Comment by eugenesmkn** [comment]
Think about whole picture.
You need to have:
- authentication info: email, password and username (why do we need the username? where do we use it?)
- profile details: first name, last name and email (could be different from the email above)
- links

Any ideas?

You could use a database schema diagrams service to illustrate it. For example, https://dbdiagram.io/home

**Comment by Washubrnfg85** [comment]
Thanks for your link. It should help.
I'll check it out in the evening.

**Comment by Washubrnfg85** [comment]
<iframe width="560" height="315" src='https://dbdiagram.io/e/65722e0c56d8064ca09be431/65722f9956d8064ca09bf531'> </iframe>

**Comment by eugenesmkn** [comment]
@Washubrnfg85 refer to #9

**Comment by Washubrnfg85** [comment]
Take a look at PR. 
I suggest to create some div or area where we could see the actual profile details. Or at least they should be displayed on input fields. What do you prefer?
