### ISSUE TITLE
Update user profile picture

### ISSUE THREAD

**Issue by eugenesmkn** [eugenesimakin/link-sharing-app#6]
- [x] Users should be able to see their current profile picture at the page. If they didn't upload the picture yet, then they should see a placeholder.
- [x] Users should be able to update their profile picture.
- [x] Users should not be able to upload images which size is more than 1024x1024px

**Comment by Washubrnfg85** [comment]
> Users should not be able to upload images which size is more than 1024x1024px

If I understand correctly, two different images with width and height of 1024px can have different size in bytes depending on bit depth, resolution etc.
We gonna limit file size or number of pixels?

**Comment by eugenesmkn** [comment]
Number of pixels and file types.

**Comment by eugenesmkn** [comment]
This is actually an optional task. You can postpone it until user's public page implemented.

**Comment by Washubrnfg85** [comment]
All right.
